steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/crawlforai'
      - '.'
    dir: '.'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/crawlforai']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'crawlforai'
      - '--gen2'
      - '--region=us-central1'
      - '--trigger-http'
      - '--runtime=python310'
      - '--entry-point=handle_request'
      - '--docker-repository=gcr.io/$PROJECT_ID/crawlforai'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY